routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');



Route::resource('marcas', App\Http\Controllers\marcasController::class);


Route::resource('modelos', App\Http\Controllers\modelosController::class);


Route::resource('versiones', App\Http\Controllers\versionesController::class);


Route::resource('estados', App\Http\Controllers\estadosController::class);


Route::resource('movilidades', App\Http\Controllers\movilidadesController::class);


Route::resource('plantillas', App\Http\Controllers\plantillasController::class);


Route::resource('repPlantillas', App\Http\Controllers\rep_plantillasController::class);


Route::resource('vehiculos', App\Http\Controllers\vehiculosController::class);


Route::resource('productos', App\Http\Controllers\productosController::class);

//mostrar desde controlador en public/XXXXX
Route::get('/qr_generate', [App\Http\Controllers\productosController::class, 'qr_generate'])->name('qr_generate');
Route::get('/nextid', [App\Http\Controllers\productosController::class, 'nextid'])->name('nextid');
Route::get('/nextid2', [App\Http\Controllers\productosController::class, 'nextid2'])->name('nextid2');
Route::post('/imprimir', [App\Http\Controllers\productosController::class, 'imprimir'])->name('imprimir');

Route::get('/getplantilla/{id}', [App\Http\Controllers\productosController::class, 'getPlantilla'])->name('getplantilla');

app/Models/vehiculos.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class vehiculos
 * @package App\Models
 * @version November 4, 2021, 7:39 pm UTC
 *
 * @property string $nombre
 * @property integer $version_id
 * @property integer $inidesarme
 * @property integer $preciocompra
    * @property string $imagen
 * @property string $descripcion
 */
class vehiculos extends Model
{
    //use SoftDeletes;

    use HasFactory;

    public $table = 'vehiculos';
    

   // protected $dates = ['deleted_at'];



    public $fillable = [
        'nombre',
        'version_id',
        'inidesarme',
        'preciocompra',
        'imagen',
        'descripcion'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'version_id' => 'integer',
        'inidesarme' => 'integer',
        'preciocompra' => 'integer',
        'imagen' => 'string',
        'descripcion' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required',
        'version_id' => 'required',
        'inidesarme' => 'required',
        'preciocompra' => 'numeric'
    ];

    public function version()
    {
        return $this->belongsTo(versiones::class, 'version_id');
    }   

    // una vehiculo tiene muchos productos
    public function productos()
    {
        return $this->hasMany(productos::class, 'vehiculo_id');
    } 
}

app/Http/Controllers/vehiculosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatevehiculosRequest;
use App\Http\Requests\UpdatevehiculosRequest;
use App\Repositories\vehiculosRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class vehiculosController extends AppBaseController
{
    /** @var  vehiculosRepository */
    private $vehiculosRepository;

    public function __construct(vehiculosRepository $vehiculosRepo)
    {
        $this->vehiculosRepository = $vehiculosRepo;
    }

    /**
     * Display a listing of the vehiculos.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $vehiculos = $this->vehiculosRepository->all();

        return view('vehiculos.index')
            ->with('vehiculos', $vehiculos);
    }

    /**
     * Show the form for creating a new vehiculos.
     *
     * @return Response
     */
    public function create()
    {
        return view('vehiculos.create');
    }

    /**
     * Store a newly created vehiculos in storage.
     *
     * @param CreatevehiculosRequest $request
     *
     * @return Response
     */
    public function store(CreatevehiculosRequest $request)
    {
        //$input = $request->all();
        //$vehiculos = $this->vehiculosRepository->create($input);
        $vehiculos = $this->vehiculosRepository->createVehiculo($request);

        Flash::success(__('messages.saved', ['model' => __('models/vehiculos.singular')]));

        return redirect(route('vehiculos.index'));
    }

    /**
     * Display the specified vehiculos.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $vehiculos = $this->vehiculosRepository->find($id);

        if (empty($vehiculos)) {
            Flash::error(__('messages.not_found', ['model' => __('models/vehiculos.singular')]));

            return redirect(route('vehiculos.index'));
        }

        return view('vehiculos.show')->with('vehiculos', $vehiculos);
    }

    /**
     * Show the form for editing the specified vehiculos.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $vehiculos = $this->vehiculosRepository->find($id);

        if (empty($vehiculos)) {
            Flash::error(__('messages.not_found', ['model' => __('models/vehiculos.singular')]));

            return redirect(route('vehiculos.index'));
        }

        return view('vehiculos.edit')->with('vehiculos', $vehiculos);
    }

    /**
     * Update the specified vehiculos in storage.
     *
     * @param int $id
     * @param UpdatevehiculosRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatevehiculosRequest $request)
    {
        $vehiculos = $this->vehiculosRepository->find($id);

        if (empty($vehiculos)) {
            Flash::error(__('messages.not_found', ['model' => __('models/vehiculos.singular')]));

            return redirect(route('vehiculos.index'));
        }

        $file = $request->file('imagen');

        if($file){
                //return 'viene imagen';
            $vehiculos = $this->vehiculosRepository->updateVehiculo($request,$id);
        }else{
                //return 'no viene imagen';
            $vehiculos = $this->vehiculosRepository->update($request->all(), $id);
        }

        Flash::success(__('messages.updated', ['model' => __('models/vehiculos.singular')]));

        return redirect(route('vehiculos.index'));
    }

    /**
     * Remove the specified vehiculos from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        
        try {
                    $vehiculos = $this->vehiculosRepository->find($id);

                    if (empty($vehiculos)) {
                        Flash::error(__('messages.not_found', ['model' => __('models/vehiculos.singular')]));

                        return redirect(route('vehiculos.index'));
                    }

                    $this->vehiculosRepository->delete($id);

                    Flash::success(__('messages.deleted', ['model' => __('models/vehiculos.singular')]));

                    return redirect(route('vehiculos.index'));

            } catch(\Exception $exception){

                    //dd($exception);
                    //$errormsg = 'No Customer to de!' .$exception->getCode();
                    //return Response::json(['errormsg'=>$errormsg]);
                    return back()->with('msj', 'Existen rejistros asociados');
                   //return redirect(route('vehiculos.index'));
                }



    }
}

resources/views/vehiculos/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/vehiculos.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/vehiculos.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('vehiculos.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'vehiculos.store', 'files' => true]) !!}
                                    <div class="row">
                                        @include('vehiculos.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/vehiculos/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/vehiculos.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/vehiculos.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('vehiculos.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($vehiculos, ['route' => ['vehiculos.update', $vehiculos->id], 'method' => 'patch', 'files' => true]) !!}
                                        <div class="row">
                                            @include('vehiculos.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/vehiculos/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', __('models/vehiculos.fields.nombre').':') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Version Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('version_id', __('models/vehiculos.fields.version_id').':') !!}
    {!! Form::select('version_id', $versioneItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Inidesarme Field -->
<div class="form-group col-sm-6">
    {!! Form::label('inidesarme', __('models/vehiculos.fields.inidesarme').':') !!}
    {!! Form::text('inidesarme', null, ['class' => 'form-control']) !!}
</div>

<!-- Preciocompra Field -->
<div class="form-group col-sm-6">
    {!! Form::label('preciocompra', __('models/vehiculos.fields.preciocompra').':') !!}
    {!! Form::text('preciocompra', null, ['class' => 'form-control']) !!}
</div>

<!-- Imagen Field -->
<div class="form-group col-sm-6">
    {!! Form::label('imagen', __('models/vehiculos.fields.imagen').':') !!}
    <input type="file" name="imagen[]" id="imagen" multiple class="form-control">

</div>

<!-- Descripcion Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('descripcion', __('models/vehiculos.fields.descripcion').':') !!}
    {!! Form::textarea('descripcion', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('vehiculos.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/vehiculos/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/vehiculos.plural')
@endsection
@section('content')

@if(session()->has('msj'))                    
                    <script type="text/javascript">
                        swal("Imposible eliminar!", "Existen registros asociados!", "error");
                    </script>
@endif
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/vehiculos.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('vehiculos.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('vehiculos.table')
            </div>
       </div>
   </div>
    
    </section>
@endsection

resources/views/vehiculos/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/vehiculos.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/vehiculos.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('vehiculos.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('vehiculos.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/vehiculos/show_fields.blade.php
<div class="row">
    <div class="card-header">
        <h4>{{ $vehiculos->nombre }}</h4>                    
        <div align="right">
            {!! Form::open(['route' => ['productos.destroy', $vehiculos->id], 'method' => 'delete']) !!}
               <div class='btn-group'>
                <a href="{!! route('vehiculos.edit', [$vehiculos->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                   {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
               </div>
            {!! Form::close() !!}
        </div>
      </div>
    <div class="col-12 col-md-6 col-lg-6">
        <div class="card">
          <div class="card-body">
            <ul class="list-group">          
                <li class="list-group-item">Version: {{ $vehiculos->version->nombre }}</li>
                <li class="list-group-item">Inicio desarme: {{ $vehiculos->inidesarme }}</li>
                <li class="list-group-item">Precio compra: ${{ number_format($vehiculos->preciocompra, 0, ',', '.') }}</li>
                <li class="list-group-item">Descripcion: {{ $vehiculos->descripcion }}</li>
                <li class="list-group-item">Creado el {{ $vehiculos->created_at }} y actualizado el{{ $vehiculos->updated_at }}</li>

            </ul>
            </ul>
          </div>
        </div>           
    </div>

    <div class="col-12 col-md-6 col-lg-6">
        <div class="card">
          <div class="card-body">
            <ul class="list-group" align="center"> 
                @if(is_array(json_decode($vehiculos->imagen)))
                @foreach(json_decode($vehiculos->imagen) as $image)
                <li class="list-group-item">
                       
                    <img width="240" height="240" src="{{ asset('endesarme/' . $image) }}"></li> 
                    @endforeach
                    @else
                     <li class="list-group-item">
                       
                    <img width="240" height="240" src="{{ asset('endesarme/' . $vehiculos->imagen[0]) }}"></li> 
                    @endif
          </div>
        </div>          
    </div>
</div>


<div class="table-responsive">
    <h4>Repuestos de {{ $vehiculos->nombre }}</h4>
    <div class="section-header-breadcrumb">
        <a href="{{ route('productos.create', ['idvec'=>$vehiculos->id])}}" class="btn btn-primary form-btn">Craer nuevo repuesto <i class="fas fa-plus"></i></a>
    </div>
    <br>
    <table class="table" id="productos-table">
        <thead>
            <tr>
                <th>@lang('models/productos.fields.nombre')</th>
        <th>@lang('models/productos.fields.precio')</th>
        <th>@lang('models/productos.fields.estado_id')</th>
        <th>@lang('models/productos.fields.movilidad_id')</th>
        <th>@lang('models/productos.fields.bodega')</th>
        <th>@lang('models/productos.fields.codrepinter')</th>
        <!-- <th>@lang('models/productos.fields.codrepfab')</th> -->
        <!-- <th>@lang('models/productos.fields.codigobarra')</th> -->
        <th>@lang('models/productos.fields.stock')</th>
        <th>@lang('models/productos.fields.imagen')</th>
        <!-- <th>@lang('models/productos.fields.qrcode')</th> -->
        <!-- <th>@lang('models/productos.fields.descripcion')</th> -->
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($vehiculos->productos as $productos)
            <tr>
            <td><a href="{!! route('productos.show', [$productos->id]) !!}">{{ $productos->nombre }}</a></td>
            <td>${{ number_format($productos->precio, 0, ',', '.') }}</td>
            <td>{{ $productos->estado->nombre }}</td>
            <td>
                 @switch($productos->movilidad_id)
                        @case(2)
                            <a href='#' class="badge badge-warning">{{ $productos->movilidad->nombre }}</a>                            
                            @break
                        @case(3)
                            <a href='#' class="badge badge-success">{{ $productos->movilidad->nombre }}</a>                          
                          @break
                        @default
                            <a href='#' class="badge badge-light">{{ $productos->movilidad->nombre }}</a>                          
                        @break
                @endswitch
            </td>
            <td>{{ $productos->bodega }}</td>
            <td>{{ $productos->codrepinter }}</td>
            <!-- <td>{{ $productos->codrepfab }}</td> -->
            <!-- <td>{{ $productos->codigobarra }}</td> -->
            <td>{{ $productos->stock }}</td>
            <td><img height="50" src="{{ asset('upload/' . $productos->imagen) }}"></td>
            <!-- <td>{{ $productos->qrcode }}</td> -->
            <!-- <td>{{ $productos->descripcion }}</td> -->
                       <td class=" text-center">
                           {!! Form::open(['route' => ['productos.destroy', $productos->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('productos.show', [$productos->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('productos.edit', [$productos->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/vehiculos/table.blade.php
<div class="table-responsive">
    <table class="table" id="vehiculos-table">
        <thead>
            <tr>
                <th>@lang('models/vehiculos.fields.nombre')</th>
        <th>@lang('models/vehiculos.fields.version_id')</th>
        <th>@lang('models/vehiculos.fields.inidesarme')</th>
        <th>@lang('models/vehiculos.fields.preciocompra')</th>
        <th>@lang('models/vehiculos.fields.imagen')</th>
        
                <th >@lang('crud.action')</th>



            </tr>
        </thead>
        <tbody>
        @foreach($vehiculos as $vehiculos)
            <tr>
            <td><a href="{!! route('vehiculos.show', [$vehiculos->id]) !!}">{{ $vehiculos->nombre }}</a></td>
            <td>{{ $vehiculos->version->nombre }}</td>
            <td>{{ $vehiculos->inidesarme }}</td>
            <td>${{ number_format($vehiculos->preciocompra, 0, ',', '.') }}</td>
            <td><img height="50" src="{{ asset('endesarme/' . json_decode($vehiculos->imagen)[0]) }}"></td>
          
                       <td class=" text-center">
                           {!! Form::open(['route' => ['vehiculos.destroy', $vehiculos->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('vehiculos.show', [$vehiculos->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('vehiculos.edit', [$vehiculos->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                  
            </tr>
        @endforeach
        </tbody>
    </table>
</div>


<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


<!--Data Table-->
<script type="text/javascript"  src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js" defer></script>


<script>
   $(document).ready( function () {

    $('#vehiculos-table').DataTable();
} );
</script>