routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');



Route::resource('marcas', App\Http\Controllers\marcasController::class);


Route::resource('modelos', App\Http\Controllers\modelosController::class);


Route::resource('versiones', App\Http\Controllers\versionesController::class);


Route::resource('estados', App\Http\Controllers\estadosController::class);


Route::resource('movilidades', App\Http\Controllers\movilidadesController::class);


Route::resource('plantillas', App\Http\Controllers\plantillasController::class);


Route::resource('repPlantillas', App\Http\Controllers\rep_plantillasController::class);


Route::resource('vehiculos', App\Http\Controllers\vehiculosController::class);


Route::resource('productos', App\Http\Controllers\productosController::class);

//mostrar desde controlador en public/XXXXX
Route::get('/qr_generate', [App\Http\Controllers\productosController::class, 'qr_generate'])->name('qr_generate');
Route::get('/nextid', [App\Http\Controllers\productosController::class, 'nextid'])->name('nextid');
Route::get('/nextid2', [App\Http\Controllers\productosController::class, 'nextid2'])->name('nextid2');
Route::post('/imprimir', [App\Http\Controllers\productosController::class, 'imprimir'])->name('imprimir');

Route::get('/getplantilla/{id}', [App\Http\Controllers\productosController::class, 'getPlantilla'])->name('getplantilla');

app/Models/rep_plantillas.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class rep_plantillas
 * @package App\Models
 * @version October 29, 2021, 12:31 pm UTC
 *
 * @property string $nombre
 * @property integer $precio
 * @property integer $plantilla_id
 */
class rep_plantillas extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'rep_plantillas';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'nombre',
        'precio',
        'plantilla_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'precio' => 'integer',
        'plantilla_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required',
        'precio' => 'required',
        'plantilla_id' => 'required'
    ];

    public function plantilla()
    {
        return $this->belongsTo(plantillas::class, 'plantilla_id');
    }

    
}

app/Http/Controllers/rep_plantillasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Createrep_plantillasRequest;
use App\Http\Requests\Updaterep_plantillasRequest;
use App\Repositories\rep_plantillasRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class rep_plantillasController extends AppBaseController
{
    /** @var  rep_plantillasRepository */
    private $repPlantillasRepository;

    public function __construct(rep_plantillasRepository $repPlantillasRepo)
    {
        $this->repPlantillasRepository = $repPlantillasRepo;
    }

    /**
     * Display a listing of the rep_plantillas.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $repPlantillas = $this->repPlantillasRepository->all();

        return view('rep_plantillas.index')
            ->with('repPlantillas', $repPlantillas);
    }

    /**
     * Show the form for creating a new rep_plantillas.
     *
     * @return Response
     */
    public function create()
    {
        return view('rep_plantillas.create');
    }

    /**
     * Store a newly created rep_plantillas in storage.
     *
     * @param Createrep_plantillasRequest $request
     *
     * @return Response
     */
    public function store(Createrep_plantillasRequest $request)
    {
        $input = $request->all();

        $repPlantillas = $this->repPlantillasRepository->create($input);

        Flash::success(__('messages.saved', ['model' => __('models/repPlantillas.singular')]));

        return redirect(route('repPlantillas.index'));
    }

    /**
     * Display the specified rep_plantillas.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $repPlantillas = $this->repPlantillasRepository->find($id);

        if (empty($repPlantillas)) {
            Flash::error(__('messages.not_found', ['model' => __('models/repPlantillas.singular')]));

            return redirect(route('repPlantillas.index'));
        }

        return view('rep_plantillas.show')->with('repPlantillas', $repPlantillas);
    }

    /**
     * Show the form for editing the specified rep_plantillas.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $repPlantillas = $this->repPlantillasRepository->find($id);

        if (empty($repPlantillas)) {
            Flash::error(__('messages.not_found', ['model' => __('models/repPlantillas.singular')]));

            return redirect(route('repPlantillas.index'));
        }

        return view('rep_plantillas.edit')->with('repPlantillas', $repPlantillas);
    }

    /**
     * Update the specified rep_plantillas in storage.
     *
     * @param int $id
     * @param Updaterep_plantillasRequest $request
     *
     * @return Response
     */
    public function update($id, Updaterep_plantillasRequest $request)
    {
        $repPlantillas = $this->repPlantillasRepository->find($id);

        if (empty($repPlantillas)) {
            Flash::error(__('messages.not_found', ['model' => __('models/repPlantillas.singular')]));

            return redirect(route('repPlantillas.index'));
        }

        $repPlantillas = $this->repPlantillasRepository->update($request->all(), $id);

        Flash::success(__('messages.updated', ['model' => __('models/repPlantillas.singular')]));

        return redirect(route('repPlantillas.index'));
    }

    /**
     * Remove the specified rep_plantillas from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $repPlantillas = $this->repPlantillasRepository->find($id);

        if (empty($repPlantillas)) {
            Flash::error(__('messages.not_found', ['model' => __('models/repPlantillas.singular')]));

            return redirect(route('repPlantillas.index'));
        }

        $this->repPlantillasRepository->delete($id);

        Flash::success(__('messages.deleted', ['model' => __('models/repPlantillas.singular')]));

        return redirect(route('repPlantillas.index'));
    }
}

resources/views/rep_plantillas/create.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.add_new') @lang('models/repPlantillas.singular')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">@lang('crud.add_new') @lang('models/repPlantillas.singular')</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('repPlantillas.index') }}" class="btn btn-primary">@lang('crud.back')</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'repPlantillas.store']) !!}
                                    <div class="row">
                                        @include('rep_plantillas.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/rep_plantillas/edit.blade.php
@extends('layouts.app')
@section('title')
    @lang('crud.edit') @lang('models/repPlantillas.singular')
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">@lang('crud.edit') @lang('models/repPlantillas.singular')</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('repPlantillas.index') }}"  class="btn btn-primary">@lang('crud.back')</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($repPlantillas, ['route' => ['repPlantillas.update', $repPlantillas->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('rep_plantillas.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/rep_plantillas/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', __('models/repPlantillas.fields.nombre').':') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Precio Field -->
<div class="form-group col-sm-6">
    {!! Form::label('precio', __('models/repPlantillas.fields.precio').':') !!}
    {!! Form::text('precio', null, ['class' => 'form-control']) !!}
</div>

<!-- Plantilla Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('plantilla_id', __('models/repPlantillas.fields.plantilla_id').':') !!}
    {!! Form::select('plantilla_id', $plantillaItems, null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('crud.save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('repPlantillas.index') }}" class="btn btn-light">@lang('crud.cancel')</a>
</div>

resources/views/rep_plantillas/index.blade.php
@extends('layouts.app')
@section('title')
     @lang('models/repPlantillas.plural')
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>@lang('models/repPlantillas.plural')</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('repPlantillas.create')}}" class="btn btn-primary form-btn">@lang('crud.add_new')<i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('rep_plantillas.table')
            </div>
       </div>
   </div>
    
    </section>
@endsection

resources/views/rep_plantillas/show.blade.php
@extends('layouts.app')
@section('title')
    @lang('models/repPlantillas.singular')  @lang('crud.details') 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>@lang('models/repPlantillas.singular') @lang('crud.details')</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('repPlantillas.index') }}"
                 class="btn btn-primary form-btn float-right">@lang('crud.back')</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('rep_plantillas.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/rep_plantillas/show_fields.blade.php
<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', __('models/repPlantillas.fields.nombre').':') !!}
    <p>{{ $repPlantillas->nombre }}</p>
</div>

<!-- Precio Field -->
<div class="form-group">
    {!! Form::label('precio', __('models/repPlantillas.fields.precio').':') !!}
    <p>{{ $repPlantillas->precio }}</p>
</div>

<!-- Plantilla Id Field -->
<div class="form-group">
    {!! Form::label('plantilla_id', __('models/repPlantillas.fields.plantilla_id').':') !!}
    <p>{{ $repPlantillas->plantilla_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', __('models/repPlantillas.fields.created_at').':') !!}
    <p>{{ $repPlantillas->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', __('models/repPlantillas.fields.updated_at').':') !!}
    <p>{{ $repPlantillas->updated_at }}</p>
</div>

resources/views/rep_plantillas/table.blade.php
<div class="table-responsive">
    <table class="table" id="repPlantillas-table">
        <thead>
            <tr>
                <th>@lang('models/repPlantillas.fields.nombre')</th>
        <th>@lang('models/repPlantillas.fields.precio')</th>
        <th>@lang('models/repPlantillas.fields.plantilla_id')</th>
                <th colspan="3">@lang('crud.action')</th>
            </tr>
        </thead>
        <tbody>
        @foreach($repPlantillas as $repPlantillas)
            <tr>
                       <td>{{ $repPlantillas->nombre }}</td>
            <td>{{ $repPlantillas->precio }}</td>
            <td>{{ $repPlantillas->plantilla->nombre }}</td>
                       <td class=" text-center">
                           {!! Form::open(['route' => ['repPlantillas.destroy', $repPlantillas->id], 'method' => 'delete']) !!}
                           <div class='btn-group'>
                               <a href="{!! route('repPlantillas.show', [$repPlantillas->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                               <a href="{!! route('repPlantillas.edit', [$repPlantillas->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                               {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("'.__('crud.are_you_sure').'")']) !!}
                           </div>
                           {!! Form::close() !!}
                       </td>
                   </tr>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


<!--Data Table-->
<script type="text/javascript"  src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js" defer></script>


<script>
   $(document).ready( function () {

    $('#repPlantillas-table').DataTable();
} );
</script>